//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAzureStatus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAzureStatus.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This [MicrosoftParentPhoneProductName] application developed by [AppAuthorName]. Current Windows Azure apps include WAZDash (Service Dashboard) &amp; WAZUp (Deployments)..
        /// </summary>
        public static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DFBerry.
        /// </summary>
        public static string AppAuthorName {
            get {
                return ResourceManager.GetString("AppAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wazup.berryintl.com.
        /// </summary>
        public static string AppAzureCloudLocation {
            get {
                return ResourceManager.GetString("AppAzureCloudLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1:81.
        /// </summary>
        public static string AppAzureCloudLocationTest {
            get {
                return ResourceManager.GetString("AppAzureCloudLocationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory =.
        /// </summary>
        public static string AppBarMenuItemTextMemory {
            get {
                return ResourceManager.GetString("AppBarMenuItemTextMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berry International.
        /// </summary>
        public static string AppCompanyName {
            get {
                return ResourceManager.GetString("AppCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to berryintl.com.
        /// </summary>
        public static string AppCompanyURL {
            get {
                return ResourceManager.GetString("AppCompanyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return all services, regardless if they have issues. .
        /// </summary>
        public static string AppConfigGetAllServicesExplanatoryText {
            get {
                return ResourceManager.GetString("AppConfigGetAllServicesExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all services, including services without any current issues.
        /// </summary>
        public static string AppConfigShowAllExplanatoryText {
            get {
                return ResourceManager.GetString("AppConfigShowAllExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connection can be found. This app will not work until a network connection is established..
        /// </summary>
        public static string AppErrorMsgNoNetworkConnection {
            get {
                return ResourceManager.GetString("AppErrorMsgNoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAZDash.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial of WAZDash has expired. You need to purchase this app in order to continue using it..
        /// </summary>
        public static string BuyAppPageTextTrialExpired {
            get {
                return ResourceManager.GetString("BuyAppPageTextTrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your trial expires, you will need to purchase this app. Why wait? Do it now..
        /// </summary>
        public static string BuyAppPageTextTrialGood {
            get {
                return ResourceManager.GetString("BuyAppPageTextTrialGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Trial.
        /// </summary>
        public static string BuyAppPageTitleTrialExpired {
            get {
                return ResourceManager.GetString("BuyAppPageTitleTrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Trial.
        /// </summary>
        public static string BuyAppPageTitleTrialGood {
            get {
                return ResourceManager.GetString("BuyAppPageTitleTrialGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impose Windows Azure Portal usage rules. Stop/Start/Delete/SwapVips buttons only available if deployment status is READY or SUSPENDED.
        /// </summary>
        public static string ConfigApplyPortalUsageRulesExplanatoryText {
            get {
                return ResourceManager.GetString("ConfigApplyPortalUsageRulesExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MicrosoftParentAzureProductName] Mobile web service is not available..
        /// </summary>
        public static string ErrorMsgAzureMobileWebServiceDown {
            get {
                return ResourceManager.GetString("ErrorMsgAzureMobileWebServiceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionHandling.cs - ReturnException: exception caught.
        /// </summary>
        public static string ExceptionExceptionFileCaughtException {
            get {
                return ResourceManager.GetString("ExceptionExceptionFileCaughtException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string ExceptionMsg1 {
            get {
                return ResourceManager.GetString("ExceptionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-generated problem report.
        /// </summary>
        public static string ExceptionSubjectTitle {
            get {
                return ResourceManager.GetString("ExceptionSubjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string ExceptionTextPartAppVersionNumber {
            get {
                return ResourceManager.GetString("ExceptionTextPartAppVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex.Message:.
        /// </summary>
        public static string ExceptionTextPartExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionTextPartExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex.StackTrace:.
        /// </summary>
        public static string ExceptionTextPartExceptionStackTrace {
            get {
                return ResourceManager.GetString("ExceptionTextPartExceptionStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionHandling.cs |Extra: .
        /// </summary>
        public static string ExceptionTextPartExtra {
            get {
                return ResourceManager.GetString("ExceptionTextPartExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex.Type .
        /// </summary>
        public static string ExceptionTypeName {
            get {
                return ResourceManager.GetString("ExceptionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Report.
        /// </summary>
        public static string ExceptionTypeTitle {
            get {
                return ResourceManager.GetString("ExceptionTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppName] developed by [Companyname] ([CompanyURL]) copyright [YearDate]. Built on [NowDateTime]..
        /// </summary>
        public static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you use this [MicrosoftParentPhoneProductName] application, you must 1) create an account at [AppWebsiteURL], and 2) associate your [MicrosoftParentAzureProductName] resources with that account. This requires that you create a certificate on [AppWebsiteURL], then upload/register that certificate with your [MicrosoftParentAzureProductName] Account. For more detailed instructions, continue to [AppWebsiteURL]..
        /// </summary>
        public static string HelpBeforePhone {
            get {
                return ResourceManager.GetString("HelpBeforePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application allows you to view status information about your [MicrosoftParentAzureProductName] resources. This requires that you have an account at [AppWebsiteURL], have added [MicrosoftParentAzureProductName] resources to that account..
        /// </summary>
        public static string HelpIntroText {
            get {
                return ResourceManager.GetString("HelpIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a username and password from [AppWebsiteURL]. This username and password is required for each sync back to grab [MicrosoftParentAzureProductName] system status..
        /// </summary>
        public static string HelpOnPhone {
            get {
                return ResourceManager.GetString("HelpOnPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppName] support provided by email. Send email support to [EmailSupport].
        /// </summary>
        public static string HelpSupport {
            get {
                return ResourceManager.GetString("HelpSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Using this App, WAZDash displays status information about your [MicrosoftParentAzureProductName] deployments. 
        ///Before you use this [MicrosoftParentPhoneProductName] application, you must 1) create an account at [AppWebsiteURL], and 2) register your [MicrosoftParentAzureProductName] subscription id with that account. Next download the security certificate from WAZDash, upload to your [MicrosoftParentAzureProductName] Account. 
        ///
        ///One time only, before you use this app
        ///Create a user account on [AppWe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string LiteralVersion {
            get {
                return ResourceManager.GetString("LiteralVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name and password from account created on [AppWebsiteURL]. Do not enter your [MicrosoftParentAzureProductName] user name and password. .
        /// </summary>
        public static string LoginHelpText {
            get {
                return ResourceManager.GetString("LoginHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Azure.
        /// </summary>
        public static string MicrosoftParentAzureProductName {
            get {
                return ResourceManager.GetString("MicrosoftParentAzureProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone 7 (WP7).
        /// </summary>
        public static string MicrosoftParentPhoneProductName {
            get {
                return ResourceManager.GetString("MicrosoftParentPhoneProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deployments found. Possible reasons include: 1) subscription is not registered on WAZDash website 2) corresponding certificate is not uploaded to Windows Azure 3) Hosting Service currently has no deployments..
        /// </summary>
        public static string NoDeploymentsFoundExtendedTextMsg {
            get {
                return ResourceManager.GetString("NoDeploymentsFoundExtendedTextMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically refresh from the web every 10 minutes.
        /// </summary>
        public static string SettingsRefreshRate {
            get {
                return ResourceManager.GetString("SettingsRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question, feature request, or bug:.
        /// </summary>
        public static string SupportEmailBody {
            get {
                return ResourceManager.GetString("SupportEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MicrosoftParentPhoneProductName] App Support Request.
        /// </summary>
        public static string SupportEmailSubject {
            get {
                return ResourceManager.GetString("SupportEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wp7@BerryIntl.com.
        /// </summary>
        public static string SupportEmailToEmailAddress {
            get {
                return ResourceManager.GetString("SupportEmailToEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (TRIAL OVER).
        /// </summary>
        public static string TrialExpiredText {
            get {
                return ResourceManager.GetString("TrialExpiredText", resourceCulture);
            }
        }
    }
}
